### ISSUE TITLE
Get User, Sort Product

### ISSUE THREAD

**Issue by quannq-comartek** [comartek/fs-clone-tinwin-distributor#44]
https://github.com/comartek/fs-clone-tinwin-distributor/pull/45

**Comment by quannq-comartek** [comment]
@phuongna-comartek @hoang-comartek

**Comment by quannq-comartek** [comment]
@phuongna-comartek e vừa push lên ạ, e quên mất, a check lại cho e với ạ

**Comment by phuongna-comartek** [comment]
@quannq-comartek  resolve conflict
